const host = 'https://api.goxx.ru'
export default {
    uc: {
        bindEmail: `${host}/uc/approve/bind/email`,
        getEmailCode: `${host}/uc/bind/email/code`,
        bindMobilePhone: `${host}/uc/approve/bind/phone`,
        getMobilePhoneCode: `${host}/uc/mobile/bind/code`,
        changeMobilePhone: `${host}/uc/approve/change/phone`,
        login: `${host}/uc/login`,
        checkLogin: `${host}/uc/check/login`,
        logout: `${host}/uc/loginout`,
        wallet: `${host}/uc/asset/wallet`,
        rechargeable: `${host}/uc/address/rechargeable`,
        depositRecords: `${host}/uc/asset/deposit/records`,
        withdrawCode: `${host}/uc/withdrawcode/record`,
        withdraw: `${host}/uc/withdraw/record`,
        legalWalletWithdraw: `${host}/uc/legal-wallet-transaction`  + `?type=1`,
        legalWalletRecharge: `${host}/uc/legal-wallet-transaction`  + `?type=0`,
        securitySetting: `${host}/uc/approve/security/setting`,
        passesName: `${host}/uc/office/passes/names`,
        history: `${host}/uc/asset/transaction/all`,
        infoWithdrawCode: `${host}/uc/withdrawcode/apply/info`,
        applyWithDrawCode: `${host}/uc/withdrawcode/apply/recharge`,
        savedAddresses: `${host}/uc/address/withdrawable`,
        deleteAddress: `${host}/uc/address/delete`,
        addAddress: `${host}/uc/address/add`,
        businessStatus: `${host}/uc/approve/certified/business/status`,
        myLimit: `${host}/uc/limits/my`,
        limits: `${host}/uc/limits`,
        createRecharge: `${host}/uc/address/create-recharge`,
        // paymentTypesWithdraw: `${host}/uc/legal-wallet-withdraw/payment-types`,
        addressWithdraw: `${host}/uc/address/withdrawable`,
        coinFull: `${host}/uc/coin/full`,
        withdrawCrypto: `${host}/uc/withdraw/create`,
        withdrawCodeApplyCode: `${host}/uc/withdrawcode/apply/code`,
        telegramUrl: `${host}/uc/approve/bind/telegram/url`,
        telegramInfo: `${host}/uc/approve/bind/telegram/info`,
        telegramAccept: `${host}/uc/approve/bind/telegram/accept`,
        telegramUnbind: `${host}/uc/approve/unbind/telegram`,
        bindUsername: `${host}/uc/approve/bind/username`,
        sendCode: `${host}/uc/reset/email/code`,
        registerEmail: `${host}/uc/register/email`,
        registerCode: `${host}/uc/reg/email/code`,
        allTimeZone: `${host}/uc/approve/time-zone`,
        bindGoogleAuth: `${host}/uc/google/googleAuth`,
        unBindGoogleAuth: `${host}/uc/google/jcgoogle`,
        sendGoogleAuth: `${host}/uc/google/sendgoogle`,
        accessToken: `${host}/uc/approve/verification/accessToken`,
        paymentTypes: `${host}/uc/payment/paymentTypes`,
        generateUrl: `${host}/uc/approve/verification/generateUrl`,
        changeLang: `${host}/uc/approve/change/language`,
        currencies: `${host}/uc/aml/currencies`,
        amlPrice: `${host}/uc/aml/price`,
        amlCheck: `${host}/uc/aml/check`,
        amlHistory: `${host}/uc/aml/page-query`,
    },
    exchange: {
        entrustCurrent: `${host}/exchange/order/personal/current`,
        entrustHistory: `${host}/exchange/order/personal/history`,
        cancelOrder: `${host}/exchange/order/cancel`,
        orderAdd: `${host}/exchange/order/add`,
    },
    otc: {
        myOrder: `${host}/otc/order/self`,
        myAd: `${host}/otc/offers/all`,
        takeOf: `${host}/otc/offers/off/shelves`,
        takeOn: `${host}/otc/offers/on/shelves`,
        remove: `${host}/otc/offers/delete`,
        unit:`${host}/otc/offers/page-by-unit`,
        page:`${host}/otc/offers/page`,
        createOrderBuy:`${host}/otc/order/buy`,
        createOrderSell:`${host}/otc/order/sell`,
        createOffer:`${host}/otc/offers/create`,
        addPaymentType:`${host}/otc/offers/ask/paymentType`,
        coinParams:`${host}/otc/coin/all`,
        createOfferShelves:`${host}/otc/offers/create/on/shelves`,

    },
    market: {
        symbolThumb: `${host}/market/symbol-thumb`,
        latestTrade: `${host}/market/latest-trade`,
        exchangePlate:  `${host}/market/exchange-plate-mini`,
    }
}